#include <stdio.h>
#include "jr_lvgl.h"
#include "jerryscript-ext/handlers.h"
#include "jerryscript-ext/properties.h"

static const jerry_const_entry_t jerry_constant_entry_list[] = {
    JERRY_CONST_ENTRY("LV_ALIGN_DEFAULT",          LV_ALIGN_DEFAULT),
    JERRY_CONST_ENTRY("LV_ALIGN_TOP_LEFT",         LV_ALIGN_TOP_LEFT),
    JERRY_CONST_ENTRY("LV_ALIGN_TOP_MID",          LV_ALIGN_TOP_MID),
    JERRY_CONST_ENTRY("LV_ALIGN_TOP_RIGHT",        LV_ALIGN_TOP_RIGHT),
    JERRY_CONST_ENTRY("LV_ALIGN_BOTTOM_LEFT",      LV_ALIGN_BOTTOM_LEFT),
    JERRY_CONST_ENTRY("LV_ALIGN_BOTTOM_MID",       LV_ALIGN_BOTTOM_MID),
    JERRY_CONST_ENTRY("LV_ALIGN_BOTTOM_RIGHT",     LV_ALIGN_BOTTOM_RIGHT),
    JERRY_CONST_ENTRY("LV_ALIGN_LEFT_MID",         LV_ALIGN_LEFT_MID),
    JERRY_CONST_ENTRY("LV_ALIGN_RIGHT_MID",        LV_ALIGN_RIGHT_MID),
    JERRY_CONST_ENTRY("LV_ALIGN_CENTER",           LV_ALIGN_CENTER),
    JERRY_CONST_ENTRY("LV_ALIGN_OUT_TOP_LEFT",     LV_ALIGN_OUT_TOP_LEFT),
    JERRY_CONST_ENTRY("LV_ALIGN_OUT_TOP_MID",      LV_ALIGN_OUT_TOP_MID),
    JERRY_CONST_ENTRY("LV_ALIGN_OUT_TOP_RIGHT",    LV_ALIGN_OUT_TOP_RIGHT),
    JERRY_CONST_ENTRY("LV_ALIGN_OUT_BOTTOM_LEFT",  LV_ALIGN_OUT_BOTTOM_LEFT),
    JERRY_CONST_ENTRY("LV_ALIGN_OUT_BOTTOM_MID",   LV_ALIGN_OUT_BOTTOM_MID),
    JERRY_CONST_ENTRY("LV_ALIGN_OUT_BOTTOM_RIGHT", LV_ALIGN_OUT_BOTTOM_RIGHT),
    JERRY_CONST_ENTRY("LV_ALIGN_OUT_LEFT_TOP",     LV_ALIGN_OUT_LEFT_TOP),
    JERRY_CONST_ENTRY("LV_ALIGN_OUT_LEFT_MID",     LV_ALIGN_OUT_LEFT_MID),
    JERRY_CONST_ENTRY("LV_ALIGN_OUT_LEFT_BOTTOM",  LV_ALIGN_OUT_LEFT_BOTTOM),
    JERRY_CONST_ENTRY("LV_ALIGN_OUT_RIGHT_TOP",    LV_ALIGN_OUT_RIGHT_TOP),
    JERRY_CONST_ENTRY("LV_ALIGN_OUT_RIGHT_MID",    LV_ALIGN_OUT_RIGHT_MID),
    JERRY_CONST_ENTRY("LV_ALIGN_OUT_RIGHT_BOTTOM", LV_ALIGN_OUT_RIGHT_BOTTOM),
    JERRY_CONST_LIST_END(),
};

void jr_gbl_const_init(void)
{
    jerry_value_t global_obj = jerry_current_realm();
    jr_register_global_constant_list(global_obj, jerry_constant_entry_list);
    jerry_value_free(global_obj);
}

